---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: hellonodejs
  labels:
    app: hellonodejs
  annotations:
    kubernetes.io/ingress.class: contour-corp
spec:
  routes:
    - match: /
      services:
        - name: hellonodejs
          port: 80
  virtualhost:
    fqdn: hellonodejs-{{NAMESPACE}}.corp.{{DNS_NAME}}.ethos.adobe.net
    tls:
      secretName: heptio-contour/cluster-ssl-corp
